version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fugi_serverpod
      POSTGRES_PASSWORD: "szXQBbCHBNUF1C61iWBXCMUmzkJJcTT8"
    volumes:
      - fugi_serverpod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "3yXdECQTP236KKu0ObUSagg5U2zEfr7N"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  fugi_serverpod_data:
